name: Trigger by tag
on:
  push:
    tags:
      - '*'
    branches:
      - main
jobs:
  Trigger-by-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        if: ${{ startsWith(github.ref_name, 'lambda-deploy' }}
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.ref }} ${{ github.ref_name }} ${{ github.ref_type }}"

