name: Trigger by tag
on:
  push:
    tags:
      - '*'
    branches:
      - main
jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
  Trigger-lambda:
    if: startsWith(github.ref_name, 'lambda-deploy')
    runs-on: ubuntu-latest
    steps:
      - run: ls ${{ github.workspace }}
      - run: echo "lambda-deploy The ${{ github.ref }} ${{ github.ref_name }} ${{ github.ref_type }}"
  Trigger-infra-nada:
    if: startsWith(github.ref_name, 'infra-nada')
    runs-on: ubuntu-latest
    steps:
      - run: echo "infra-nada ${{ github.ref }} ${{ github.ref_name }} ${{ github.ref_type }}"

