name: Lint (shell)

on:
  push:
    tags:
      - '*'
    branches:
      - main


jobs:
  Trigger-by-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
